[package]
name = "rustctl-backend"
version = "0.1.0"
edition = "2024"

[dependencies.axum-server]
version = "0.7.2"
default-features = false
features = ["tls-rustls"]

[dependencies.chrono]
version = "0.4.41"
default-features = false
features = ["serde", "alloc", "now"]

[dependencies.uuid]
version = "1.17.0"
default-features = false
features = ["v4", "serde"]

[dependencies.console-subscriber]
version = "0.4.1"
default-features = false

[dependencies.tower-http]
version = "0.6.4"
default-features = false
features = ["cors", "fs"]

[dependencies.clap]
version = "4.5.39"
default-features = false
features = ["derive", "std"]

[dependencies.serde]
version = "1.0.219"
default-features = false
features = ["derive"]

[dependencies.serde_json]
version = "1.0.140"
default-features = false

[dependencies.futures]
version = "0.3.31"
default-features = false

[dependencies.axum]
version = "0.8.4"
default-features = false
features = ["ws"]

[dependencies.tokio]
version = "1.45.1"
default-features = false
features = ["fs", "tracing", "rt"]
