[package]
name = "rustctl-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6.0", features = [] }
futures-util = { version = "0.3.31", features = ["sink"] }
gloo-net = "0.6.0"
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen-futures = "0.4.50"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
