[package]
name         = "frontend"
edition      = "2024"
rust-version = { workspace = true }

[features]
default = [ "web" ]
web     = [ "dioxus/web" ]

[dependencies]
base64 = { workspace = true, features = [
  "alloc",
] }

dioxus = { workspace = true, features = [
  "devtools",
  "launch",
  "lib",
  "logger",
] }

futures-util = { workspace = true, features = [
] }

gloo-net = { workspace = true, features = [
  "http",
  "json",
  "websocket",
] }

gloo-timers = { workspace = true, features = [
] }

js-sys = { workspace = true, features = [
] }

serde_json = { workspace = true, features = [
] }

shared = { path = "../shared" }

wasm-bindgen-futures = { workspace = true, features = [
] }

wasm-bindgen = { workspace = true, features = [
] }

web-sys = { workspace = true, features = [
  "AuthenticatorSelectionCriteria",
  "CredentialCreationOptions",
  "CredentialRequestOptions",
  "CredentialsContainer",
  "Navigator",
  "PublicKeyCredential",
  "PublicKeyCredentialCreationOptions",
  "PublicKeyCredentialRequestOptions",
  "PublicKeyCredentialRpEntity",
  "PublicKeyCredentialUserEntity",
  "UserVerificationRequirement",
  "Window",
] }
