[package]
name         = "frontend"
edition      = "2024"
rust-version = { workspace = true }

[features]
default = [ "web" ]
web     = [ "dioxus/web" ]

[dependencies]
dioxus = { workspace = true, features = [
  "devtools",
  "launch",
  "lib",
  "logger",
] }

futures-util = { workspace = true, features = [
] }

gloo-net = { workspace = true, features = [
  "websocket",
] }

gloo-timers = { workspace = true, features = [
] }
