#cloud-config
users:
  - name: rustctl
    groups: sudo
    shell: /usr/bin/fish
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN0pUS3zNMEM1cGCYj7TfT2ADP0PYQrGiZHlB8kFxQXf

package_update: true
packages:
  - curl
  - fish

write_files:
  - path: /etc/sudoers.d/rustctl
    content: |
      rustctl ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart rustctl.service
      rustctl ALL=(ALL) NOPASSWD: /usr/bin/systemctl reboot

runcmd:
  - mkdir -p /tmp/rustctl
  - chown rustctl:rustctl /tmp/rustctl
