[toolchain]
# There's no particular reason for this version of the toolchain. Latest stable
# as of 2025-09-21 is 1.89.0. I just like pinning exact versions.
channel = "1.89.0"

# There's no particular reason for musl target. I just prefer statically linked
# binaries for no apparent reason.
targets = [
  "x86_64-unknown-linux-musl",
]
