[package]
edition      = "2024"
name         = "backend"
rust-version = { workspace = true }

[dependencies]
axum-server = { workspace = true, features = [
  "rustls",
  "tls-rustls",
] }

axum = { workspace = true, features = [
  "http1", # for compatibility with curl for testing purposes
  "json",
  "tokio",
] }

clap = { workspace = true, default-features = false, features = [
  "color",
  "derive",
  "error-context",
  "help",
  "std",
  "suggestions",
  "usage",
] }

futures-util = { workspace = true, default-features = false, features = [
] }

log4rs = { workspace = true, default-features = false, features = [
 "console_appender",
] }

log = { workspace = true, features = [
] }

nix = { workspace = true, features = [
  "fs",
  "signal",
] }

rand = { workspace = true, features = [
] }

rcgen = { workspace = true, features = [
  "aws_lc_rs",
  "crypto",
  "pem",
] }

reqwest = { workspace = true, features = [
] }

serde = { workspace = true, features = [
  "serde_derive",
] }

serde_json = { workspace = true, features = [
] }

serde_yaml = { workspace = true, features = [
] }

tokio = { workspace = true, features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "process",
  "rt",
  "time",
] }

tokio-tungstenite = { workspace = true, features = [
  "connect",
  "stream",
] }

tower-http = { workspace = true, features = [
  "fs",
] }
