[package]
edition      = "2024"
name         = "backend"
version      = { workspace = true }
rust-version = { workspace = true }

[dependencies]
axum = { workspace = true, features = [
  "http1", # for compatibility with curl for testing purposes
  "json",
  "tokio",
] }

chrono = { workspace = true, features = [
  "serde",
] }

clap = { workspace = true, default-features = false, features = [
  "color",
  "derive",
  "error-context",
  "help",
  "std",
  "suggestions",
  "usage",
] }

futures-util = { workspace = true, default-features = false, features = [
] }

hyper-util = { workspace = true, default-features = false, features = [
  "http1",
  "server-graceful",
] }

hyper = { workspace = true, default-features = false, features = [
] }

libcrux-ml-dsa = { workspace = true, default-features = false, features = [
  "mldsa87",
] }

log4rs = { workspace = true, default-features = false, features = [
 "console_appender",
] }

log = { workspace = true, features = [
] }

nix = { workspace = true, features = [
  "fs",
  "signal",
] }

openssl = { workspace = true, features = [
  "vendored",
] }

rand = { workspace = true, features = [
  "sys_rng",
] }

rcgen = { workspace = true, features = [
  "aws_lc_rs",
  "crypto",
  "pem",
] }

reqwest = { workspace = true, features = [
] }

rustls-pki-types = { workspace = true, features = [
  "alloc",
] }

rustls = { workspace = true, features = [
  "aws_lc_rs",
  "prefer-post-quantum",
  "std",
] }

serde = { workspace = true, features = [
  "serde_derive",
] }

serde_json = { workspace = true, features = [
] }

serde_yaml = { workspace = true, features = [
] }

shared = { path = "../shared" }

tokio = { workspace = true, features = [
  "fs",
  "io-util",
  "macros",
  "net",
  "process",
  "rt",
  "time",
] }

tokio-postgres = { workspace = true, features = [
  "runtime",
  "with-chrono-0_4",
  "with-serde_json-1",
] }

tokio-rustls = { workspace = true, features = [
] }

tokio-tungstenite = { workspace = true, features = [
  "connect",
  "stream",
] }

tower-http = { workspace = true, features = [
  "fs",
] }

tower = { workspace = true, features = [
] }

url = { workspace = true, features = [
] }

uuid = { workspace = true, features = [
] }

webauthn-rs = { workspace = true, features = [
  "conditional-ui",
] }
