[package]
name = "rustctl-common"
edition = "2024"

[dependencies.serde]
workspace = true
features = [
  "derive",
  "std",
]

[dependencies.chrono]
workspace = true
features = [
  "serde",
]

[dependencies.uuid]
workspace = true
features = [
  "serde",
]

[dependencies.dioxus-core]
workspace = true

[dependencies.dioxus]
workspace = true
features = [
  "macro",
]
