[package]
name    = "rustctl-web"
edition = "2024"

[features]
default = ["web"]
web     = ["dioxus/web"]

[dependencies]
dioxus               = { workspace = true, features = ["web", "html", "hooks", "signals", "launch", "macro"] }
futures-util         = { workspace = true, features = ["sink"] }
gloo-net             = { workspace = true, features = ["websocket"] }
gloo-timers          = { workspace = true, features = ["futures"] }
rustctl-common       = { workspace = true, features = [] }
serde_json           = { workspace = true, features = [] }
serde                = { workspace = true, features = ["derive"] }
wasm-bindgen-futures = { workspace = true, features = [] }
web-sys              = { workspace = true, features = ["HtmlBodyElement", "CssStyleDeclaration", "HtmlElement"] }
