[package]
name = "tui-websocket-client"
edition = "2024"

[dependencies.tokio]
workspace = true
features  = [
  "macros",
  "rt",
  "time",
]

[dependencies.tokio-tungstenite]
workspace = true
features  = [
  "connect",
]

[dependencies.futures-util]
workspace = true
features  = [
]

[dependencies.crossterm]
workspace = true
features  = [
  "events",
]

[dependencies.ratatui]
workspace = true
features  = [
  "crossterm",
]

[dependencies.tokio-util]
workspace = true
features  = [
]

[dependencies.chrono]
workspace = true
features  = [
  "now",
]

[dependencies.serde_json]
workspace = true
features  = [
  "alloc",
]

[dependencies.rustctl-common]
workspace = true
features  = [
]
