[package]
name    = "rustctl-common"
edition = "2024"

[dependencies.serde]
workspace = true
features  = [
  "derive",
  "std",
]

[dependencies.chrono]
workspace = true
features  = [
  "serde",
]

[dependencies.uuid]
workspace = true
features  = [
  "serde",
]

[dependencies.dioxus-core]
workspace = true

[dependencies.dioxus]
workspace = true
features  = [
  "macro",
]

[dependencies.axum]
workspace = true
features  = [
  "ws",
]

[dependencies.serde_json]
workspace = true
features  = [
]
