[package]
name    = "rustctl-common"
edition = "2024"

[dependencies]
axum         = { workspace = true, features = ["ws"] }
chrono       = { workspace = true, features = ["serde"] }
dioxus-core  = { workspace = true, features = [] }
dioxus       = { workspace = true, features = ["macro"] }
serde_json   = { workspace = true, features = [] }
serde        = { workspace = true, features = ["derive", "std"] }
uuid         = { workspace = true, features = ["serde"] }
