[package]
name = "rustctl-frontend"
version = "0.1.0"
edition = "2024"

[dependencies.rustctl-common]
path = "../rustctl-common"

[dependencies.dioxus]
version = "0.6.3"
default-features = false
features = [
  "asset",
  "cli-config",
  "devtools",
  "document",
  "file_engine",
  "hooks",
  "html",
  "launch",
  "logger",
  "macro",
  "mounted",
  "signals",
  "warnings",
]

[dependencies.futures-util]
version = "0.3.31"
default-features = false
features = ["sink"]

[dependencies.gloo-net]
version = "0.6.0"
default-features = false
features = ["websocket"]

[dependencies.serde]
version = "1.0.219"
default-features = false
features = ["derive"]

[dependencies.wasm-bindgen-futures]
version = "0.4.50"
default-features = false

[features]
default = ["web"]
web = ["dioxus/web"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
